# -*- coding: utf-8 -*-
"""Data Analysis Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXlNyT6k0I6msfaDXZHhACPxPIZ_3Mwr
"""

import pandas as pd
import numpy as np

df=pd.read_csv('House_Price.csv')
df.head()

#information for data
df.info()

#five point summary

df.describe()

#Mean

df.age.mean()

#Median

df.crime_rate.median()

#Standard derivation

df.crime_rate.std()

#Variance

df.crime_rate.var()

Missing Value

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

sns.boxplot(x='age',data=df)

sns.boxplot(x='age',y='teachers',data=df)

#Histogram

df.hist(figsize=(10,15))

sns.histplot(df['age'], kde=True)
Count plot

sns.countplot(x='crime_rate', data=df)

sns.countplot(x='age',hue='crime_rate', data=df)

Removing value

df_num = df.drop(['age','crime_rate','price'], axis=1)
df_num


Corelation

for column in df_num.select_dtypes(include=['object']).columns:
    df_num[column] = df_num[column].map({'YES': 1, 'NO': 0})

correlation = df_num.corr()
correlation


# Select only numeric columns from df_num
numeric_columns = df_num.select_dtypes(include=np.number).columns
correlation = df_num[numeric_columns].corr()
correlation

Heat map

sns.heatmap(correlation, annot=True)

sns.jointplot(x='age', y='crime_rate', data=df)
